name: Rotate Github App Private Key
description: Rotate a Github App Private in Azure Key Vault

inputs:
  app_id:
    description: 'The ID of your GitHub App.'
    required: true
  installation_id:
    description: 'The installation ID of the target repository or organization.'
    required: true
  kv_url:
    description: 'The URL of your Azure Key Vault.'
    required: true
  kv_secret_name:
    description: 'The name of the secret in Azure Key Vault.'
    required: true
  token:
    description: 'The GitHub token to authenticate with GitHub.'
    required: true
  azure_client_id:
    description: 'The client ID for authenticating with Azure.'
    required: true
  azure_client_secret:
    description: 'The client secret for authenticating with Azure.'
    required: true
  azure_tenant_id:
    description: 'The tenant ID for authenticating with Azure.'
    required: true
  azure_subscription_id:
    description: 'The subscription ID for accessing Azure resources.'
    required: true

outputs:
  token:
    description: 'The generated GitHub App token'

runs:
  using: 'docker'
  image: 'docker://ghcr.io/arctiqdemos/rotate-github-app-private-key:1.0.0'
